[repository]
name = "hypr-monitor"
authors = ["Fabio Elvedi"]

[hypr-monitor]
description = "Monitor management plugin for Hyprland"
authors = ["Fabio Elvedi"]
output = "build/libhypr-monitor.so"
build = [
    "cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -B build",
    "cmake --build build"
]

